spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 18595739675@163.com
    password: 1124512195
    default-encoding: utf-8
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.gaohanghang.springbootmanagebooks.entity
  configuration:
    map-underscore-to-camel-case: true

mail:
  fromMail:
    addr: 18595739675@163.com